
#define WM_TRAYNOTIFY (WM_APP + 1)
#define WM_CHANGES_SAVED (WM_APP + 2)

// The resource compiler doesn't understand __LINE__ or __COUNTER__.
// It also can't parse spaces in definitions.
// It also doesn't calculate dialog defitions, so those can't be relative.

#define ICON_DEFAULT 1100

#define MENU_STANDBYTRAY 2100
#define MENU_STANDBYTRAY_SHOW (MENU_STANDBYTRAY+1)
#define MENU_STANDBYTRAY_CLOSE (MENU_STANDBYTRAY+2)

#define MENU_TRAY 2200
#define MENU_TRAY_SHOW (MENU_TRAY+1)
#define MENU_TRAY_STANDBY (MENU_TRAY+2)
#define MENU_TRAY_CLOSE (MENU_TRAY+3)

#define MENU_MAINDIALOG 2300
#define MENU_MAINDIALOG_FILE_ADD_ENTRY (MENU_MAINDIALOG+1)
#define MENU_MAINDIALOG_FILE_STANDBY (MENU_MAINDIALOG+2)
#define MENU_MAINDIALOG_FILE_EXIT (MENU_MAINDIALOG+3)
#define MENU_MAINDIALOG_TOOLS_CONFIGURE_AUTOSTART (MENU_MAINDIALOG+4)
#define MENU_MAINDIALOG_TOOLS_SHOW_HIDDEN_ENTRIES (MENU_MAINDIALOG+5)
#define MENU_MAINDIALOG_TOOLS_SHOW_DATABASE (MENU_MAINDIALOG+6)
#define MENU_MAINDIALOG_TOOLS_MERGE_TEXT (MENU_MAINDIALOG+7)
#define MENU_MAINDIALOG_ABOUT_INFO (MENU_MAINDIALOG+99)

#define MENU_LISTBOXCONTEXT 2400
#define MENU_LISTBOXCONTEXT_EDIT (MENU_LISTBOXCONTEXT+1)
#define MENU_LISTBOXCONTEXT_HIDESHOW (MENU_LISTBOXCONTEXT+2)

#define DIALOG_PASSWORD 10100
#define DIALOG_PASSWORD_EDIT_PASSWORD (DIALOG_PASSWORD+1)
#define DIALOG_PASSWORD_EDIT_FILENAME (DIALOG_PASSWORD+2)
#define DIALOG_PASSWORD_BUTTON_OK (DIALOG_PASSWORD+3)
#define DIALOG_PASSWORD_BUTTON_CANCEL (DIALOG_PASSWORD+4)
#define DIALOG_PASSWORD_BUTTON_SELECTFILE (DIALOG_PASSWORD+5)

#define DIALOG_MAIN 10200
#define DIALOG_MAIN_EDIT_SEARCH (DIALOG_MAIN+1)
#define DIALOG_MAIN_BUTTON_COPY_RESET (DIALOG_MAIN+2)
#define DIALOG_MAIN_BUTTON_ADD (DIALOG_MAIN+3)
#define DIALOG_MAIN_BUTTON_SETTINGS (DIALOG_MAIN+4)
#define DIALOG_MAIN_LISTBOX_LIST (DIALOG_MAIN+5)

#define DIALOG_EDITDATA 10300
#define DIALOG_EDITDATA_EDIT_NAME (DIALOG_EDITDATA+1)
#define DIALOG_EDITDATA_EDIT_USERNAME (DIALOG_EDITDATA+2)
#define DIALOG_EDITDATA_EDIT_PASSWORD (DIALOG_EDITDATA+3)
#define DIALOG_EDITDATA_EDIT_COMMENT (DIALOG_EDITDATA+4)
#define DIALOG_EDITDATA_BUTTON_SAVE (DIALOG_EDITDATA+5)
#define DIALOG_EDITDATA_BUTTON_CANCEL (DIALOG_EDITDATA+6)
#define DIALOG_EDITDATA_BUTTON_GENERATE (DIALOG_EDITDATA+7)
#define DIALOG_EDITDATA_BUTTON_HISTORY (DIALOG_EDITDATA+8)
#define DIALOG_EDITDATA_CHECKBOX_LETTERS (DIALOG_EDITDATA+9)
#define DIALOG_EDITDATA_CHECKBOX_NUMBERS (DIALOG_EDITDATA+10)
#define DIALOG_EDITDATA_CHECKBOX_SPECIAL (DIALOG_EDITDATA+11)
#define DIALOG_EDITDATA_CHECKBOX_EXTRA (DIALOG_EDITDATA+12)
#define DIALOG_EDITDATA_EDIT_EXTRA (DIALOG_EDITDATA+13)
#define DIALOG_EDITDATA_EDIT_PWLENGTH (DIALOG_EDITDATA+14)
#define DIALOG_EDITDATA_EDIT_PWSTRENGTH (DIALOG_EDITDATA+15)

#define DIALOG_HISTORY 10400
#define DIALOG_HISTORY_EDIT_HISTORY (DIALOG_HISTORY+1)

#define DIALOG_SHOWDATABASE 10500
#define DIALOG_SHOWDATABASE_EDIT_TEXT (DIALOG_SHOWDATABASE+1)
#define DIALOG_SHOWDATABASE_BUTTON_COPY (DIALOG_SHOWDATABASE+2)

#define DIALOG_MERGETEXT 10600
#define DIALOG_MERGETEXT_EDIT_TEXT (DIALOG_MERGETEXT+1)
#define DIALOG_MERGETEXT_BUTTON_MERGE (DIALOG_MERGETEXT+2)

#define DIALOG_AUTOSTART 10700
#define DIALOG_AUTOSTART_BUTTON_NORMAL (DIALOG_AUTOSTART+1)
#define DIALOG_AUTOSTART_BUTTON_STANDBY (DIALOG_AUTOSTART+2)
#define DIALOG_AUTOSTART_BUTTON_REMOVE (DIALOG_AUTOSTART+3)
#define DIALOG_AUTOSTART_BUTTON_CANCEL (DIALOG_AUTOSTART+4)
