
#define WM_TRAYNOTIFY (WM_APP + 1)
#define WM_CHANGES_SAVED (WM_APP + 2)
#define WM_SETTINGS_APPLIED (WM_APP + 3)
#define WM_CLEAR_CLIPBOARD (WM_APP + 4)
#define WM_CHECK_INACTIVE_TIME (WM_APP + 5)

// The resource compiler doesn't understand __LINE__ or __COUNTER__.
// It also can't parse spaces in definitions.
// It also doesn't calculate dialog definitions, so those can't be relative.

#define ICON_DEFAULT 1100

#define MENU_STANDBYTRAY 2100
#define MENU_STANDBYTRAY_SHOW (MENU_STANDBYTRAY+1)
#define MENU_STANDBYTRAY_CLOSE (MENU_STANDBYTRAY+2)

#define MENU_TRAY 2200
#define MENU_TRAY_SHOW (MENU_TRAY+1)
#define MENU_TRAY_STANDBY (MENU_TRAY+2)
#define MENU_TRAY_CLOSE (MENU_TRAY+3)

#define MENU_MAINDIALOG 2300
#define MENU_MAINDIALOG_FILE_ADD_ENTRY (MENU_MAINDIALOG+1)
#define MENU_MAINDIALOG_FILE_STANDBY (MENU_MAINDIALOG+2)
#define MENU_MAINDIALOG_FILE_EXIT (MENU_MAINDIALOG+3)
#define MENU_MAINDIALOG_TOOLS_SETTINGS (MENU_MAINDIALOG+4)
#define MENU_MAINDIALOG_TOOLS_ALWAYS_ON_TOP (MENU_MAINDIALOG+5)
#define MENU_MAINDIALOG_TOOLS_SHOW_HIDDEN_ENTRIES (MENU_MAINDIALOG+6)
#define MENU_MAINDIALOG_TOOLS_SHOW_DATABASE (MENU_MAINDIALOG+7)
#define MENU_MAINDIALOG_TOOLS_MERGE_TEXT (MENU_MAINDIALOG+8)
#define MENU_MAINDIALOG_ABOUT_INFO (MENU_MAINDIALOG+99)

#define MENU_LISTBOXCONTEXT 2400
#define MENU_LISTBOXCONTEXT_EDIT (MENU_LISTBOXCONTEXT+1)
#define MENU_LISTBOXCONTEXT_HIDESHOW (MENU_LISTBOXCONTEXT+2)

#define DIALOG_PASSWORD 10100
#define DIALOG_PASSWORD_EDIT_PASSWORD (DIALOG_PASSWORD+1)
#define DIALOG_PASSWORD_EDIT_FILENAME (DIALOG_PASSWORD+2)
#define DIALOG_PASSWORD_BUTTON_OK (DIALOG_PASSWORD+3)
#define DIALOG_PASSWORD_BUTTON_CANCEL (DIALOG_PASSWORD+4)
#define DIALOG_PASSWORD_BUTTON_SELECTFILE (DIALOG_PASSWORD+5)

#define DIALOG_MAIN 10200
#define DIALOG_MAIN_EDIT_SEARCH (DIALOG_MAIN+1)
#define DIALOG_MAIN_BUTTON_COPY_RESET (DIALOG_MAIN+2)
#define DIALOG_MAIN_BUTTON_ADD (DIALOG_MAIN+3)
#define DIALOG_MAIN_BUTTON_SETTINGS (DIALOG_MAIN+4)
#define DIALOG_MAIN_LISTBOX_LIST (DIALOG_MAIN+5)

#define DIALOG_EDITDATA 10300
#define DIALOG_EDITDATA_EDIT_NAME (DIALOG_EDITDATA+1)
#define DIALOG_EDITDATA_EDIT_USERNAME (DIALOG_EDITDATA+2)
#define DIALOG_EDITDATA_EDIT_PASSWORD (DIALOG_EDITDATA+3)
#define DIALOG_EDITDATA_EDIT_COMMENT (DIALOG_EDITDATA+4)
#define DIALOG_EDITDATA_BUTTON_SAVE (DIALOG_EDITDATA+5)
#define DIALOG_EDITDATA_BUTTON_CANCEL (DIALOG_EDITDATA+6)
#define DIALOG_EDITDATA_BUTTON_GENERATE (DIALOG_EDITDATA+7)
#define DIALOG_EDITDATA_BUTTON_HISTORY (DIALOG_EDITDATA+8)
#define DIALOG_EDITDATA_CHECKBOX_LETTERS (DIALOG_EDITDATA+9)
#define DIALOG_EDITDATA_CHECKBOX_NUMBERS (DIALOG_EDITDATA+10)
#define DIALOG_EDITDATA_CHECKBOX_SPECIAL (DIALOG_EDITDATA+11)
#define DIALOG_EDITDATA_CHECKBOX_EXTRA (DIALOG_EDITDATA+12)
#define DIALOG_EDITDATA_EDIT_EXTRA (DIALOG_EDITDATA+13)
#define DIALOG_EDITDATA_EDIT_PWLENGTH (DIALOG_EDITDATA+14)
#define DIALOG_EDITDATA_EDIT_PWSTRENGTH (DIALOG_EDITDATA+15)

#define DIALOG_HISTORY 10400
#define DIALOG_HISTORY_EDIT_HISTORY (DIALOG_HISTORY+1)

#define DIALOG_SHOWDATABASE 10500
#define DIALOG_SHOWDATABASE_EDIT_TEXT (DIALOG_SHOWDATABASE+1)
#define DIALOG_SHOWDATABASE_BUTTON_COPY (DIALOG_SHOWDATABASE+2)

#define DIALOG_MERGETEXT 10600
#define DIALOG_MERGETEXT_EDIT_TEXT (DIALOG_MERGETEXT+1)
#define DIALOG_MERGETEXT_BUTTON_MERGE (DIALOG_MERGETEXT+2)

#define DIALOG_SETTINGS 10700
#define DIALOG_SETTINGS_BUTTON_APPLY (DIALOG_SETTINGS+1)
#define DIALOG_SETTINGS_BUTTON_CANCEL (DIALOG_SETTINGS+2)
#define DIALOG_SETTINGS_COMBOBOX_AUTOSTART (DIALOG_SETTINGS+3)
#define DIALOG_SETTINGS_COMBOBOX_USERNAME_TIMEOUT (DIALOG_SETTINGS+4)
#define DIALOG_SETTINGS_COMBOBOX_PASSWORD_TIMEOUT (DIALOG_SETTINGS+5)
#define DIALOG_SETTINGS_COMBOBOX_AUTOTYPER_TIMEOUT (DIALOG_SETTINGS+6)
#define DIALOG_SETTINGS_COMBOBOX_IDLE_TIMEOUT (DIALOG_SETTINGS+7)
#define DIALOG_SETTINGS_COMBOBOX_CLIPBOARD_HOTKEY (DIALOG_SETTINGS+8)
#define DIALOG_SETTINGS_CHECKBOX_CLIPBOARD_HOTKEY_CTRL (DIALOG_SETTINGS+9)
#define DIALOG_SETTINGS_CHECKBOX_CLIPBOARD_HOTKEY_SHIFT (DIALOG_SETTINGS+10)
#define DIALOG_SETTINGS_CHECKBOX_CLIPBOARD_HOTKEY_ALT (DIALOG_SETTINGS+11)
#define DIALOG_SETTINGS_COMBOBOX_AUTOTYPER_HOTKEY (DIALOG_SETTINGS+12)
#define DIALOG_SETTINGS_CHECKBOX_AUTOTYPER_HOTKEY_CTRL (DIALOG_SETTINGS+13)
#define DIALOG_SETTINGS_CHECKBOX_AUTOTYPER_HOTKEY_SHIFT (DIALOG_SETTINGS+14)
#define DIALOG_SETTINGS_CHECKBOX_AUTOTYPER_HOTKEY_ALT (DIALOG_SETTINGS+15)


#define DIALOG_SETHOTKEY 10800
